INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Wii Sports', 2006, 'Nintendo', 'Wii', 'Sports', 29.02);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Super Mario Bros.', 1985, 'Nintendo', 'NES', 'Platform', 3.58);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Mario Kart Wii', 2008, 'Nintendo', 'Wii', 'Racing', 12.88);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Wii Sports Resort', 2009, 'Nintendo', 'Wii', 'Sports', 11.01);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Pokemon Red/Pokemon Blue', 1996, 'Nintendo', 'GB', 'Role-Playing', 8.89);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Tetris', 1989, 'Nintendo', 'GB', 'Puzzle', 2.26);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('New Super Mario Bros.', 2006, 'Nintendo', 'DS', 'Platform', 9.23);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Wii Play', 2006, 'Nintendo', 'Wii', 'Misc', 9.20);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('New Super Mario Bros. Wii', 2009, 'Nintendo', 'Wii', 'Platform', 7.06);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Duck Hunt', 1984, 'Nintendo', 'NES', 'Shooter', 0.63);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Nintendogs', 2005, 'Nintendo', 'DS', 'Simulation', 11.00);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Mario Kart DS', 2005, 'Nintendo', 'DS', 'Racing', 7.57);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Pokemon Gold/Pokemon Silver', 1999, 'Nintendo', 'GB', 'Role-Playing', 6.18);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Wii Fit', 2007, 'Nintendo', 'Wii', 'Sports', 8.03);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Wii Fit Plus', 2009, 'Nintendo', 'Wii', 'Sports', 8.59);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Kinect Adventures!', 2010, 'Microsoft Game Studios', 'X360', 'Misc', 4.94);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Grand Theft Auto V', 2013, 'Take-Two Interactive', 'PS3', 'Action', 9.27);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Grand Theft Auto: San Andreas', 2004, 'Take-Two Interactive', 'PS2', 'Action', 0.40);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Super Mario World', 1990, 'Nintendo', 'SNES', 'Platform', 3.75);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Brain Age: Train Your Brain in Minutes a Day', 2005, 'Nintendo', 'DS', 'Misc', 9.26);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Pokemon Diamond/Pokemon Pearl', 2006, 'Nintendo', 'DS', 'Role-Playing', 4.52);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Super Mario Land', 1989, 'Nintendo', 'GB', 'Platform', 2.71);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Super Mario Bros. 3', 1988, 'Nintendo', 'NES', 'Platform', 3.44);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Grand Theft Auto V', 2013, 'Take-Two Interactive', 'X360', 'Action', 5.31);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Grand Theft Auto: Vice City', 2002, 'Take-Two Interactive', 'PS2', 'Action', 5.49);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Pokemon Ruby/Pokemon Sapphire', 2002, 'Nintendo', 'GBA', 'Role-Playing', 3.90);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Pokemon Black/Pokemon White', 2010, 'Nintendo', 'DS', 'Role-Playing', 3.28);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Brain Age 2: More Training in Minutes a Day', 2005, 'Nintendo', 'DS', 'Puzzle', 5.36);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Gran Turismo 3: A-Spec', 2001, 'Sony Computer Entertainment', 'PS2', 'Racing', 5.09);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Call of Duty: Modern Warfare 3', 2011, 'Activision', 'X360', 'Shooter', 4.28);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Pokémon Yellow: Special Pikachu Edition', 1998, 'Nintendo', 'GB', 'Role-Playing', 5.04);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Call of Duty: Black Ops', 2010, 'Activision', 'X360', 'Shooter', 3.73);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Pokemon X/Pokemon Y', 2013, 'Nintendo', '3DS', 'Role-Playing', 4.05);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Call of Duty: Black Ops 3', 2015, 'Activision', 'PS4', 'Shooter', 5.81);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Call of Duty: Black Ops II', 2012, 'Activision', 'PS3', 'Shooter', 5.88);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Call of Duty: Black Ops II', 2012, 'Activision', 'X360', 'Shooter', 4.30);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Call of Duty: Modern Warfare 2', 2009, 'Activision', 'X360', 'Shooter', 3.63);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Call of Duty: Modern Warfare 3', 2011, 'Activision', 'PS3', 'Shooter', 5.82);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Grand Theft Auto III', 2001, 'Take-Two Interactive', 'PS2', 'Action', 4.51);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Super Smash Bros. Brawl', 2008, 'Nintendo', 'Wii', 'Fighting', 2.61);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Call of Duty: Black Ops', 2010, 'Activision', 'PS3', 'Shooter', 4.44);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Animal Crossing: Wild World', 2005, 'Nintendo', 'DS', 'Simulation', 3.52);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Mario Kart 7', 2011, 'Nintendo', '3DS', 'Racing', 3.91);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Halo 3', 2007, 'Microsoft Game Studios', 'X360', 'Shooter', 2.83);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Grand Theft Auto V', 2014, 'Take-Two Interactive', 'PS4', 'Action', 5.81);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Pokemon HeartGold/Pokemon SoulSilver', 2009, 'Nintendo', 'DS', 'Action', 2.77);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Super Mario 64', 1996, 'Nintendo', 'N64', 'Platform', 2.85);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Gran Turismo 4', 2004, 'Sony Computer Entertainment', 'PS2', 'Racing', 0.01);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Super Mario Galaxy', 2007, 'Nintendo', 'Wii', 'Platform', 3.40);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Pokemon Omega Ruby/Pokemon Alpha Sapphire', 2014, 'Nintendo', '3DS', 'Role-Playing', 3.37);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Super Mario Land 2: 6 Golden Coins', 1992, 'Nintendo', 'GB', 'Adventure', 2.04);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Grand Theft Auto IV', 2008, 'Take-Two Interactive', 'X360', 'Action', 3.10);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Gran Turismo', 1997, 'Sony Computer Entertainment', 'PS', 'Racing', 3.87);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Super Mario 3D Land', 2011, 'Nintendo', '3DS', 'Platform', 2.99);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Gran Turismo 5', 2010, 'Sony Computer Entertainment', 'PS3', 'Racing', 4.88);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Call of Duty: Modern Warfare 2', 2009, 'Activision', 'PS3', 'Shooter', 3.69);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Grand Theft Auto IV', 2008, 'Take-Two Interactive', 'PS3', 'Action', 3.76);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Super Mario All-Stars', 1993, 'Nintendo', 'SNES', 'Platform', 2.15);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Pokemon FireRed/Pokemon LeafGreen', 2004, 'Nintendo', 'GBA', 'Role-Playing', 2.65);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Super Mario 64', 2004, 'Nintendo', 'DS', 'Platform', 3.11);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Just Dance 3', 2011, 'Ubisoft', 'Wii', 'Misc', 3.15);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Call of Duty: Ghosts', 2013, 'Activision', 'X360', 'Shooter', 2.63);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Halo: Reach', 2010, 'Microsoft Game Studios', 'X360', 'Shooter', 1.98);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Mario Kart 64', 1996, 'Nintendo', 'N64', 'Racing', 1.94);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('New Super Mario Bros. 2', 2012, 'Nintendo', '3DS', 'Platform', 3.07);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Halo 4', 2012, 'Microsoft Game Studios', 'X360', 'Shooter', 2.36);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Final Fantasy VII', 1997, 'Sony Computer Entertainment', 'PS', 'Role-Playing', 2.47);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Call of Duty: Ghosts', 2013, 'Activision', 'PS3', 'Shooter', 3.73);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Just Dance 2', 2010, 'Ubisoft', 'Wii', 'Misc', 2.89);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Gran Turismo 2', 1999, 'Sony Computer Entertainment', 'PS', 'Racing', 3.42);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Call of Duty 4: Modern Warfare', 2007, 'Activision', 'X360', 'Shooter', 2.38);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Donkey Kong Country', 1994, 'Nintendo', 'SNES', 'Platform', 1.71);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Minecraft', 2013, 'Microsoft Game Studios', 'X360', 'Misc', 2.83);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Animal Crossing: New Leaf', 2012, 'Nintendo', '3DS', 'Simulation', 2.32);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Mario Party DS', 2007, 'Nintendo', 'DS', 'Misc', 1.88);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('The Elder Scrolls V: Skyrim', 2011, 'Bethesda Softworks', 'X360', 'Role-Playing', 2.86);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Super Mario Kart', 1992, 'Nintendo', 'SNES', 'Racing', 1.24);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('FIFA 16', 2015, 'Electronic Arts', 'PS4', 'Sports', 6.06);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Wii Party', 2010, 'Nintendo', 'Wii', 'Misc', 3.53);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Halo 2', 2004, 'Microsoft Game Studios', 'XB', 'Shooter', 1.53);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Mario Party 8', 2007, 'Nintendo', 'Wii', 'Misc', 2.30);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Pokemon Black 2/Pokemon White 2', 2012, 'Nintendo', 'DS', 'Role-Playing', 1.86);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('FIFA Soccer 13', 2012, 'Electronic Arts', 'PS3', 'Action', 5.05);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('The Sims 3', 2009, 'Electronic Arts', 'PC', 'Simulation', 6.42);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('GoldenEye 007', 1997, 'Nintendo', 'N64', 'Shooter', 2.01);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Mario & Sonic at the Olympic Games', 2007, 'Sega', 'Wii', 'Sports', 3.90);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Final Fantasy X', 2001, 'Sony Computer Entertainment', 'PS2', 'Role-Playing', 2.07);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Final Fantasy VIII', 1999, 'SquareSoft', 'PS', 'Role-Playing', 1.72);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Pokémon Platinum Version', 2008, 'Nintendo', 'DS', 'Role-Playing', 1.78);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Pac-Man', 1982, 'Atari', '2600', 'Puzzle', 0.45);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Grand Theft Auto: Liberty City Stories', 2005, 'Take-Two Interactive', 'PSP', 'Action', 2.83);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Super Mario Galaxy 2', 2010, 'Nintendo', 'Wii', 'Platform', 2.42);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Star Wars Battlefront (2015)', 2015, 'Electronic Arts', 'PS4', 'Shooter', 3.29);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Call of Duty: Advanced Warfare', 2014, 'Activision', 'PS4', 'Shooter', 3.30);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('The Legend of Zelda: Ocarina of Time', 1998, 'Nintendo', 'N64', 'Action', 1.89);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Crash Bandicoot 2: Cortex Strikes Back', 1997, 'Sony Computer Entertainment', 'PS', 'Platform', 2.17);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Super Mario Bros. 2', 1988, 'Nintendo', 'NES', 'Platform', 1.18);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Super Smash Bros. for Wii U and 3DS', 2014, 'Nintendo', '3DS', 'Fighting', 1.35);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Call of Duty: World at War', 2008, 'Activision', 'X360', 'Shooter', 1.90);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Battlefield 3', 2011, 'Electronic Arts', 'X360', 'Shooter', 2.13);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('The Legend of Zelda: Twilight Princess', 2006, 'Nintendo', 'Wii', 'Action', 2.19);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Call of Duty: Black Ops 3', 2015, 'Activision', 'XOne', 'Shooter', 2.09);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Just Dance', 2009, 'Ubisoft', 'Wii', 'Misc', 3.03);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Battlefield 3', 2011, 'Electronic Arts', 'PS3', 'Shooter', 2.93);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Need for Speed Underground', 2003, 'Electronic Arts', 'PS2', 'Racing', 2.83);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Tekken 3', 1998, 'Sony Computer Entertainment', 'PS', 'Fighting', 2.22);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Crash Bandicoot 3: Warped', 1998, 'Sony Computer Entertainment', 'PS', 'Platform', 1.75);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Super Smash Bros. Melee', 2001, 'Nintendo', 'GC', 'Fighting', 1.04);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Mario Kart 8', 2014, 'Nintendo', 'WiiU', 'Racing', 2.07);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Fallout 4', 2015, 'Bethesda Softworks', 'PS4', 'Role-Playing', 3.15);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Mario Kart: Double Dash!!', 2003, 'Nintendo', 'GC', 'Racing', 1.77);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Just Dance 4', 2012, 'Ubisoft', 'Wii', 'Misc', 2.21);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('FIFA 14', 2013, 'Electronic Arts', 'PS3', 'Sports', 4.32);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Need for Speed Underground 2', 2004, 'Electronic Arts', 'PS2', 'Racing', 3.02);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Medal of Honor: Frontline', 2002, 'Electronic Arts', 'PS2', 'Shooter', 2.75);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Uncharted 3: Drake''s Deception', 2011, 'Sony Computer Entertainment', 'PS3', 'Action', 2.80);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Crash Bandicoot', 1996, 'Sony Computer Entertainment', 'PS', 'Platform', 2.35);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Zumba Fitness', 2010, '505 Games', 'Wii', 'Sports', 2.64);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Gears of War 2', 2008, 'Microsoft Game Studios', 'X360', 'Shooter', 1.92);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Uncharted 2: Among Thieves', 2009, 'Sony Computer Entertainment', 'PS3', 'Action', 2.25);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Call of Duty 4: Modern Warfare', 2007, 'Activision', 'PS3', 'Shooter', 2.30);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('FIFA 12', 2011, 'Electronic Arts', 'PS3', 'Sports', 4.32);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Big Brain Academy', 2005, 'Nintendo', 'DS', 'Misc', 2.78);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Red Dead Redemption', 2010, 'Take-Two Interactive', 'PS3', 'Action', 2.61);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('FIFA 15', 2014, 'Electronic Arts', 'PS4', 'Sports', 4.29);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Donkey Kong Country Returns', 2010, 'Nintendo', 'Wii', 'Platform', 1.84);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('The Elder Scrolls V: Skyrim', 2011, 'Bethesda Softworks', 'PS3', 'Role-Playing', 2.71);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('The Legend of Zelda', 1986, 'Nintendo', 'NES', 'Action', 0.93);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Assassin''s Creed III', 2012, 'Ubisoft', 'PS3', 'Action', 2.56);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Halo: Combat Evolved', 2001, 'Microsoft Game Studios', 'XB', 'Shooter', 1.30);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Pokémon Emerald Version', 2004, 'Nintendo', 'GBA', 'Role-Playing', 1.58);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Kingdom Hearts', 2002, 'Sony Computer Entertainment', 'PS2', 'Role-Playing', 1.20);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Pokémon Crystal Version', 2000, 'Nintendo', 'GB', 'Role-Playing', 1.56);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Halo 3: ODST', 2009, 'Microsoft Game Studios', 'X360', 'Shooter', 1.35);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Red Dead Redemption', 2010, 'Take-Two Interactive', 'X360', 'Action', 1.97);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Super Mario Sunshine', 2002, 'Nintendo', 'GC', 'Platform', 1.26);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Street Fighter II: The World Warrior', 1992, 'Capcom', 'SNES', 'Fighting', 0.83);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('World of Warcraft', 2004, 'Activision', 'PC', 'Role-Playing', 6.21);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Driver', 1999, 'GT Interactive', 'PS', 'Action', 2.80);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Kinect Sports', 2010, 'Microsoft Game Studios', 'X360', 'Sports', 1.78);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Gears of War 3', 2011, 'Microsoft Game Studios', 'X360', 'Shooter', 1.62);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Gears of War', 2006, 'Microsoft Game Studios', 'X360', 'Shooter', 1.90);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Metal Gear Solid 2: Sons of Liberty', 2001, 'Konami Digital Entertainment', 'PS2', 'Action', 2.01);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Sonic the Hedgehog 2', 1992, 'Sega', 'GEN', 'Platform', 1.20);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Metal Gear Solid 4: Guns of the Patriots', 2008, 'Konami Digital Entertainment', 'PS3', 'Action', 1.74);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Metal Gear Solid', 1998, 'Konami Digital Entertainment', 'PS', 'Action', 1.83);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('The Last of Us', 2013, 'Sony Computer Entertainment Europe', 'PS3', 'Action', 2.28);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Final Fantasy XII', 2006, 'Square Enix', 'PS2', 'Role-Playing', 0.00);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('LittleBigPlanet', 2008, 'Sony Computer Entertainment', 'PS3', 'Platform', 2.05);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Dragon Quest IX: Sentinels of the Starry Skies', 2009, 'Nintendo', 'DS', 'Role-Playing', 0.69);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('LEGO Star Wars: The Complete Saga', 2007, 'LucasArts', 'Wii', 'Action', 1.63);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Resident Evil 2', 1998, 'Virgin Interactive', 'PS', 'Action', 1.47);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Tekken 2', 1996, 'Sony Computer Entertainment', 'PS', 'Fighting', 1.89);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Cooking Mama', 2006, '505 Games', 'DS', 'Simulation', 1.94);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Destiny', 2014, 'Activision', 'PS4', 'Shooter', 2.05);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Tetris', 1988, 'Nintendo', 'NES', 'Puzzle', 0.69);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Assassin''s Creed II', 2009, 'Ubisoft', 'PS3', 'Action', 1.95);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Super Smash Bros.', 1999, 'Nintendo', 'N64', 'Fighting', 0.60);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Assassin''s Creed', 2007, 'Ubisoft', 'X360', 'Adventure', 1.65);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Batman: Arkham City', 2011, 'Warner Bros. Interactive Entertainment', 'PS3', 'Action', 1.91);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Forza Motorsport 3', 2009, 'Microsoft Game Studios', 'X360', 'Racing', 1.92);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Monster Hunter Freedom Unite', 2008, 'Capcom', 'PSP', 'Role-Playing', 0.57);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Super Mario Advance', 2001, 'Nintendo', 'GBA', 'Platform', 1.24);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Mario Kart: Super Circuit', 2001, 'Nintendo', 'GBA', 'Racing', 1.64);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Super Mario World', 2001, 'Nintendo', 'GBA', 'Platform', 1.11);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Pokemon Stadium', 1999, 'Nintendo', 'N64', 'Strategy', 1.24);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Call of Duty: World at War', 2008, 'Activision', 'PS3', 'Shooter', 1.87);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Crash Bandicoot: The Wrath of Cortex', 2001, 'Universal Interactive', 'PS2', 'Platform', 2.29);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Minecraft', 2014, 'Sony Computer Entertainment', 'PS3', 'Misc', 2.51);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Final Fantasy XIII', 2009, 'Square Enix', 'PS3', 'Role-Playing', 1.24);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Dr. Mario', 1989, 'Nintendo', 'GB', 'Puzzle', 0.96);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Pokemon Pinball', 1999, 'Nintendo', 'GB', 'Misc', 1.12);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Assassin''s Creed III', 2012, 'Ubisoft', 'X360', 'Action', 1.71);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Final Fantasy IX', 2000, 'SquareSoft', 'PS', 'Role-Playing', 0.77);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Final Fantasy X-2', 2003, 'Electronic Arts', 'PS2', 'Role-Playing', 1.08);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Donkey Kong 64', 1999, 'Nintendo', 'N64', 'Platform', 0.79);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Assassin''s Creed II', 2009, 'Ubisoft', 'X360', 'Action', 1.56);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Professor Layton and the Curious Village', 2007, 'Nintendo', 'DS', 'Puzzle', 2.48);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Tomb Raider II', 1997, 'Eidos Interactive', 'PS', 'Action', 2.46);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Madden NFL 2004', 0, 'Electronic Arts', 'PS2', 'Sports', 0.26);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Dragon Quest VIII: Journey of the Cursed King', 2004, 'Square Enix', 'PS2', 'Role-Playing', 0.75);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Diablo III', 2012, 'Activision', 'PC', 'Role-Playing', 2.15);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Super Mario Bros. 3', 2003, 'Nintendo', 'GBA', 'Platform', 1.25);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('New Super Mario Bros. U', 2012, 'Nintendo', 'WiiU', 'Platform', 1.30);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Super Mario Land 3: Wario Land', 1994, 'Nintendo', 'GB', 'Platform', 0.98);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('FIFA Soccer 13', 2012, 'Electronic Arts', 'X360', 'Action', 3.48);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('The Legend of Zelda: Phantom Hourglass', 2007, 'Nintendo', 'DS', 'Action', 1.83);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Donkey Kong Country 2: Diddy''s Kong Quest', 1995, 'Nintendo', 'SNES', 'Platform', 0.74);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Tomodachi Life', 2013, 'Nintendo', '3DS', 'Simulation', 2.02);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Mario & Sonic at the Olympic Games', 2008, 'Sega', 'DS', 'Sports', 2.48);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Medal of Honor: Rising Sun', 2003, 'Electronic Arts', 'PS2', 'Shooter', 2.23);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Kirby''s Dream Land', 1992, 'Nintendo', 'GB', 'Platform', 0.61);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Fable III', 2010, 'Microsoft Game Studios', 'X360', 'Role-Playing', 1.11);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Call of Duty: Advanced Warfare', 2014, 'Activision', 'XOne', 'Shooter', 1.53);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Microsoft Flight Simulator', 1996, 'Microsoft Game Studios', 'PC', 'Simulation', 1.69);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Guitar Hero II', 2006, 'RedOctane', 'PS2', 'Misc', 0.63);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Resident Evil 5', 2009, 'Capcom', 'PS3', 'Action', 1.43);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Grand Theft Auto V', 2014, 'Take-Two Interactive', 'XOne', 'Action', 2.01);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('Grand Theft Auto: Vice City Stories', 2006, 'Take-Two Interactive', 'PSP', 'Action', 2.02);
INSERT INTO juegos (nombre, fecha, editor, plataforma, genero, eu_sales) VALUES ('FIFA Soccer 11', 2010, 'Electronic Arts', 'PS3', 'Sports', 3.29);
